name        : taglib
version     : 1.10.0
release     : 2
source      :
    - https://github.com/taglib/taglib/archive/v1.10.tar.gz : 2cd09ac6d4c4ec610aa5a0a488466bd0e0f78576581ef1f344090e397ecb9c52
license     :
    - LGPLv2.1+
    - MPL-1.1
homepage    : http://taglib.github.io/
summary     : Library to read metadata from a variety of multimedia formats
description : |
    TagLib is a library for reading and editing the meta-data of several popular audio formats. Currently it supports both ID3v1 and ID3v2 for MP3 files, Ogg Vorbis comments and ID3 tags and Vorbis comments in FLAC, MPC, Speex, WavPack TrueAudio, WAV, AIFF, MP4 and ASF files.
setup      : |
    %cmake -DWITH_ASF=ON \
        -DWITH_MP4=ON
build      : |
    %make
install    : |
    %make_install
