name       : taglib
version    : 1.11.1
release    : 6
source     :
    - https://github.com/taglib/taglib/archive/v1.11.1.tar.gz : b6d1a5a610aae6ff39d93de5efd0fdc787aa9e9dc1e7026fa4c961b26563526b
license    :
    - LGPL-2.1-or-later
    - MPL-1.1
component  : multimedia.library
homepage   : http://taglib.github.io/
summary    : Library to read metadata from a variety of multimedia formats
description: |
    TagLib is a library for reading and editing the meta-data of several popular audio formats. Currently it supports both ID3v1 and ID3v2 for MP3 files, Ogg Vorbis comments and ID3 tags and Vorbis comments in FLAC, MPC, Speex, WavPack TrueAudio, WAV, AIFF, MP4 and ASF files.
setup      : |
    %apply_patches
    %cmake -DBUILD_SHARED_LIBS=ON -DWITH_ASF=ON -DWITH_MP4=ON
build      : |
    %make
install    : |
    %make_install
